version: "3.8"

services:
  app:
    env_file:
      - .env.development
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json

  mysql:
    ports:
      - "3306:3306"
