version: "3.8"

services:
  app:
    build: .
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: db_expressjs_boilerplate
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
